// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddPersonCreatedCode is the HTTP code returned for type AddPersonCreated
const AddPersonCreatedCode int = 201

/*
AddPersonCreated person created

swagger:response addPersonCreated
*/
type AddPersonCreated struct {
}

// NewAddPersonCreated creates AddPersonCreated with default headers values
func NewAddPersonCreated() *AddPersonCreated {

	return &AddPersonCreated{}
}

// WriteResponse to the client
func (o *AddPersonCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddPersonBadRequestCode is the HTTP code returned for type AddPersonBadRequest
const AddPersonBadRequestCode int = 400

/*
AddPersonBadRequest invalid input, object invalid

swagger:response addPersonBadRequest
*/
type AddPersonBadRequest struct {
}

// NewAddPersonBadRequest creates AddPersonBadRequest with default headers values
func NewAddPersonBadRequest() *AddPersonBadRequest {

	return &AddPersonBadRequest{}
}

// WriteResponse to the client
func (o *AddPersonBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddPersonConflictCode is the HTTP code returned for type AddPersonConflict
const AddPersonConflictCode int = 409

/*
AddPersonConflict person already exists

swagger:response addPersonConflict
*/
type AddPersonConflict struct {
}

// NewAddPersonConflict creates AddPersonConflict with default headers values
func NewAddPersonConflict() *AddPersonConflict {

	return &AddPersonConflict{}
}

// WriteResponse to the client
func (o *AddPersonConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
