// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddPersonHandlerFunc turns a function with the right signature into a add person handler
type AddPersonHandlerFunc func(AddPersonParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddPersonHandlerFunc) Handle(params AddPersonParams) middleware.Responder {
	return fn(params)
}

// AddPersonHandler interface for that can handle valid add person params
type AddPersonHandler interface {
	Handle(AddPersonParams) middleware.Responder
}

// NewAddPerson creates a new http.Handler for the add person operation
func NewAddPerson(ctx *middleware.Context, handler AddPersonHandler) *AddPerson {
	return &AddPerson{Context: ctx, Handler: handler}
}

/*
	AddPerson swagger:route POST /persons admins addPerson

adds an person item

Adds an person to the system
*/
type AddPerson struct {
	Context *middleware.Context
	Handler AddPersonHandler
}

func (o *AddPerson) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddPersonParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
