// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddbankHandlerFunc turns a function with the right signature into a addbank handler
type AddbankHandlerFunc func(AddbankParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddbankHandlerFunc) Handle(params AddbankParams) middleware.Responder {
	return fn(params)
}

// AddbankHandler interface for that can handle valid addbank params
type AddbankHandler interface {
	Handle(AddbankParams) middleware.Responder
}

// NewAddbank creates a new http.Handler for the addbank operation
func NewAddbank(ctx *middleware.Context, handler AddbankHandler) *Addbank {
	return &Addbank{Context: ctx, Handler: handler}
}

/*
	Addbank swagger:route POST /banks admins addbank

adds an bank item

Adds an bank to the system
*/
type Addbank struct {
	Context *middleware.Context
	Handler AddbankHandler
}

func (o *Addbank) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddbankParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
