// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddbankCreatedCode is the HTTP code returned for type AddbankCreated
const AddbankCreatedCode int = 201

/*
AddbankCreated bank created

swagger:response addbankCreated
*/
type AddbankCreated struct {
}

// NewAddbankCreated creates AddbankCreated with default headers values
func NewAddbankCreated() *AddbankCreated {

	return &AddbankCreated{}
}

// WriteResponse to the client
func (o *AddbankCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddbankBadRequestCode is the HTTP code returned for type AddbankBadRequest
const AddbankBadRequestCode int = 400

/*
AddbankBadRequest invalid input, object invalid

swagger:response addbankBadRequest
*/
type AddbankBadRequest struct {
}

// NewAddbankBadRequest creates AddbankBadRequest with default headers values
func NewAddbankBadRequest() *AddbankBadRequest {

	return &AddbankBadRequest{}
}

// WriteResponse to the client
func (o *AddbankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddbankConflictCode is the HTTP code returned for type AddbankConflict
const AddbankConflictCode int = 409

/*
AddbankConflict bank already exists

swagger:response addbankConflict
*/
type AddbankConflict struct {
}

// NewAddbankConflict creates AddbankConflict with default headers values
func NewAddbankConflict() *AddbankConflict {

	return &AddbankConflict{}
}

// WriteResponse to the client
func (o *AddbankConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
