// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBankCreatedCode is the HTTP code returned for type GetBankCreated
const GetBankCreatedCode int = 201

/*
GetBankCreated bank found

swagger:response getBankCreated
*/
type GetBankCreated struct {
}

// NewGetBankCreated creates GetBankCreated with default headers values
func NewGetBankCreated() *GetBankCreated {

	return &GetBankCreated{}
}

// WriteResponse to the client
func (o *GetBankCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// GetBankBadRequestCode is the HTTP code returned for type GetBankBadRequest
const GetBankBadRequestCode int = 400

/*
GetBankBadRequest invalid input, object invalid

swagger:response getBankBadRequest
*/
type GetBankBadRequest struct {
}

// NewGetBankBadRequest creates GetBankBadRequest with default headers values
func NewGetBankBadRequest() *GetBankBadRequest {

	return &GetBankBadRequest{}
}

// WriteResponse to the client
func (o *GetBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetBankConflictCode is the HTTP code returned for type GetBankConflict
const GetBankConflictCode int = 409

/*
GetBankConflict bank not exists

swagger:response getBankConflict
*/
type GetBankConflict struct {
}

// NewGetBankConflict creates GetBankConflict with default headers values
func NewGetBankConflict() *GetBankConflict {

	return &GetBankConflict{}
}

// WriteResponse to the client
func (o *GetBankConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
