// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPersonCreatedCode is the HTTP code returned for type GetPersonCreated
const GetPersonCreatedCode int = 201

/*
GetPersonCreated person found

swagger:response getPersonCreated
*/
type GetPersonCreated struct {
}

// NewGetPersonCreated creates GetPersonCreated with default headers values
func NewGetPersonCreated() *GetPersonCreated {

	return &GetPersonCreated{}
}

// WriteResponse to the client
func (o *GetPersonCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// GetPersonBadRequestCode is the HTTP code returned for type GetPersonBadRequest
const GetPersonBadRequestCode int = 400

/*
GetPersonBadRequest invalid input, object invalid

swagger:response getPersonBadRequest
*/
type GetPersonBadRequest struct {
}

// NewGetPersonBadRequest creates GetPersonBadRequest with default headers values
func NewGetPersonBadRequest() *GetPersonBadRequest {

	return &GetPersonBadRequest{}
}

// WriteResponse to the client
func (o *GetPersonBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetPersonConflictCode is the HTTP code returned for type GetPersonConflict
const GetPersonConflictCode int = 409

/*
GetPersonConflict person not exists

swagger:response getPersonConflict
*/
type GetPersonConflict struct {
}

// NewGetPersonConflict creates GetPersonConflict with default headers values
func NewGetPersonConflict() *GetPersonConflict {

	return &GetPersonConflict{}
}

// WriteResponse to the client
func (o *GetPersonConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
