// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCardCreatedCode is the HTTP code returned for type GetCardCreated
const GetCardCreatedCode int = 201

/*
GetCardCreated card found

swagger:response getCardCreated
*/
type GetCardCreated struct {
}

// NewGetCardCreated creates GetCardCreated with default headers values
func NewGetCardCreated() *GetCardCreated {

	return &GetCardCreated{}
}

// WriteResponse to the client
func (o *GetCardCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// GetCardBadRequestCode is the HTTP code returned for type GetCardBadRequest
const GetCardBadRequestCode int = 400

/*
GetCardBadRequest invalid input, object invalid

swagger:response getCardBadRequest
*/
type GetCardBadRequest struct {
}

// NewGetCardBadRequest creates GetCardBadRequest with default headers values
func NewGetCardBadRequest() *GetCardBadRequest {

	return &GetCardBadRequest{}
}

// WriteResponse to the client
func (o *GetCardBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCardConflictCode is the HTTP code returned for type GetCardConflict
const GetCardConflictCode int = 409

/*
GetCardConflict card not exists

swagger:response getCardConflict
*/
type GetCardConflict struct {
}

// NewGetCardConflict creates GetCardConflict with default headers values
func NewGetCardConflict() *GetCardConflict {

	return &GetCardConflict{}
}

// WriteResponse to the client
func (o *GetCardConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
