// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bank-microservice/api/models"
	"fmt"

	"github.com/spf13/cobra"
)

// Schema cli for Bank

// register flags to command
func registerModelBankFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerBankPropBic(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerBankPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerBankPropBic(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive bic uint32 is not supported by go-swagger cli yet

	return nil
}

func registerBankPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Required. `

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelBankFlags(depth int, m *models.Bank, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, BicAdded := retrieveBankPropBicFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BicAdded

	err, NameAdded := retrieveBankPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	return nil, retAdded
}

func retrieveBankPropBicFlags(depth int, m *models.Bank, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBicName := fmt.Sprintf("%v.bic", cmdPrefix)
	if cmd.Flags().Changed(flagBicName) {

		// warning: primitive bic uint32 is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}

func retrieveBankPropNameFlags(depth int, m *models.Bank, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

		retAdded = true
	}

	return nil, retAdded
}
