// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"bank-microservice/api/client/admins"

	"github.com/spf13/cobra"
)

// makeOperationAdminsDelBankCmd returns a command to handle operation delBank
func makeOperationAdminsDelBankCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "delBank",
		Short: `Remove an bank from the system`,
		RunE:  runOperationAdminsDelBank,
	}

	if err := registerOperationAdminsDelBankParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationAdminsDelBank uses cmd flags to call endpoint api
func runOperationAdminsDelBank(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := admins.NewDelBankParams()
	if err, _ = retrieveOperationAdminsDelBankInnFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationAdminsDelBankResult(appCli.Admins.DelBank(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationAdminsDelBankParamFlags registers all flags needed to fill params
func registerOperationAdminsDelBankParamFlags(cmd *cobra.Command) error {
	if err := registerOperationAdminsDelBankInnParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationAdminsDelBankInnParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagInnDescription := `Required. bank to remove`

	var flagInnName string
	if cmdPrefix == "" {
		flagInnName = "inn"
	} else {
		flagInnName = fmt.Sprintf("%v.inn", cmdPrefix)
	}

	var flagInnDefault int64

	_ = cmd.PersistentFlags().Int64(flagInnName, flagInnDefault, flagInnDescription)

	return nil
}

func retrieveOperationAdminsDelBankInnFlag(m *admins.DelBankParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("inn") {

		var flagInnName string
		if cmdPrefix == "" {
			flagInnName = "inn"
		} else {
			flagInnName = fmt.Sprintf("%v.inn", cmdPrefix)
		}

		flagInnValue, err := cmd.Flags().GetInt64(flagInnName)
		if err != nil {
			return err, false
		}
		m.Inn = flagInnValue

	}

	return nil, retAdded
}

// parseOperationAdminsDelBankResult parses request result and return the string content
func parseOperationAdminsDelBankResult(resp0 *admins.DelBankNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning delBankNoContent is not supported

		// Non schema case: warning delBankBadRequest is not supported

		// Non schema case: warning delBankConflict is not supported

		return "", respErr
	}

	// warning: non schema response delBankNoContent is not supported by go-swagger cli yet.

	return "", nil
}
