// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"bank-microservice/api/client/admins"

	"github.com/spf13/cobra"
)

// makeOperationAdminsGetPersonCmd returns a command to handle operation getPerson
func makeOperationAdminsGetPersonCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getPerson",
		Short: `Gets an person from the system`,
		RunE:  runOperationAdminsGetPerson,
	}

	if err := registerOperationAdminsGetPersonParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationAdminsGetPerson uses cmd flags to call endpoint api
func runOperationAdminsGetPerson(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := admins.NewGetPersonParams()
	if err, _ = retrieveOperationAdminsGetPersonInnFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationAdminsGetPersonResult(appCli.Admins.GetPerson(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationAdminsGetPersonParamFlags registers all flags needed to fill params
func registerOperationAdminsGetPersonParamFlags(cmd *cobra.Command) error {
	if err := registerOperationAdminsGetPersonInnParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationAdminsGetPersonInnParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagInnDescription := `Required. get person`

	var flagInnName string
	if cmdPrefix == "" {
		flagInnName = "inn"
	} else {
		flagInnName = fmt.Sprintf("%v.inn", cmdPrefix)
	}

	var flagInnDefault int64

	_ = cmd.PersistentFlags().Int64(flagInnName, flagInnDefault, flagInnDescription)

	return nil
}

func retrieveOperationAdminsGetPersonInnFlag(m *admins.GetPersonParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("inn") {

		var flagInnName string
		if cmdPrefix == "" {
			flagInnName = "inn"
		} else {
			flagInnName = fmt.Sprintf("%v.inn", cmdPrefix)
		}

		flagInnValue, err := cmd.Flags().GetInt64(flagInnName)
		if err != nil {
			return err, false
		}
		m.Inn = flagInnValue

	}

	return nil, retAdded
}

// parseOperationAdminsGetPersonResult parses request result and return the string content
func parseOperationAdminsGetPersonResult(resp0 *admins.GetPersonCreated, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning getPersonCreated is not supported

		// Non schema case: warning getPersonBadRequest is not supported

		// Non schema case: warning getPersonConflict is not supported

		return "", respErr
	}

	// warning: non schema response getPersonCreated is not supported by go-swagger cli yet.

	return "", nil
}
