// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"bank-microservice/api/client/admins"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationAdminsIsValidCmd returns a command to handle operation isValid
func makeOperationAdminsIsValidCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "isValid",
		Short: `Check card status: if card.exists & card.valid>now() > valid = true
`,
		RunE: runOperationAdminsIsValid,
	}

	if err := registerOperationAdminsIsValidParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationAdminsIsValid uses cmd flags to call endpoint api
func runOperationAdminsIsValid(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := admins.NewIsValidParams()
	if err, _ = retrieveOperationAdminsIsValidIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationAdminsIsValidResult(appCli.Admins.IsValid(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationAdminsIsValidParamFlags registers all flags needed to fill params
func registerOperationAdminsIsValidParamFlags(cmd *cobra.Command) error {
	if err := registerOperationAdminsIsValidIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationAdminsIsValidIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. get card status`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault int64

	_ = cmd.PersistentFlags().Int64(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func retrieveOperationAdminsIsValidIDFlag(m *admins.IsValidParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetInt64(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

// parseOperationAdminsIsValidResult parses request result and return the string content
func parseOperationAdminsIsValidResult(resp0 *admins.IsValidOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*admins.IsValidOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning isValidBadRequest is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
