-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.card
(
    id integer NOT NULL,
    person_inn integer NOT NULL,
    bank_bic integer NOT NULL,
    expiries date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    inn integer NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (inn)
);

CREATE TABLE IF NOT EXISTS public.bank
(
    bic integer NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (bic)
);

ALTER TABLE IF EXISTS public.card
    ADD FOREIGN KEY (person_inn)
    REFERENCES public.person (inn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.card
    ADD FOREIGN KEY (bank_bic)
    REFERENCES public.bank (bic) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;