// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"bank-microservice/api/models"
)

// NewAddPersonParams creates a new AddPersonParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddPersonParams() *AddPersonParams {
	return &AddPersonParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddPersonParamsWithTimeout creates a new AddPersonParams object
// with the ability to set a timeout on a request.
func NewAddPersonParamsWithTimeout(timeout time.Duration) *AddPersonParams {
	return &AddPersonParams{
		timeout: timeout,
	}
}

// NewAddPersonParamsWithContext creates a new AddPersonParams object
// with the ability to set a context for a request.
func NewAddPersonParamsWithContext(ctx context.Context) *AddPersonParams {
	return &AddPersonParams{
		Context: ctx,
	}
}

// NewAddPersonParamsWithHTTPClient creates a new AddPersonParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddPersonParamsWithHTTPClient(client *http.Client) *AddPersonParams {
	return &AddPersonParams{
		HTTPClient: client,
	}
}

/*
AddPersonParams contains all the parameters to send to the API endpoint

	for the add person operation.

	Typically these are written to a http.Request.
*/
type AddPersonParams struct {

	/* Person.

	   Person to add
	*/
	Person *models.Person

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add person params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPersonParams) WithDefaults() *AddPersonParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add person params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPersonParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add person params
func (o *AddPersonParams) WithTimeout(timeout time.Duration) *AddPersonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add person params
func (o *AddPersonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add person params
func (o *AddPersonParams) WithContext(ctx context.Context) *AddPersonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add person params
func (o *AddPersonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add person params
func (o *AddPersonParams) WithHTTPClient(client *http.Client) *AddPersonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add person params
func (o *AddPersonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPerson adds the person to the add person params
func (o *AddPersonParams) WithPerson(person *models.Person) *AddPersonParams {
	o.SetPerson(person)
	return o
}

// SetPerson adds the person to the add person params
func (o *AddPersonParams) SetPerson(person *models.Person) {
	o.Person = person
}

// WriteToRequest writes these params to a swagger request
func (o *AddPersonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Person != nil {
		if err := r.SetBodyParam(o.Person); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
