// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"bank-microservice/api/models"
)

// NewAddCardParams creates a new AddCardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddCardParams() *AddCardParams {
	return &AddCardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddCardParamsWithTimeout creates a new AddCardParams object
// with the ability to set a timeout on a request.
func NewAddCardParamsWithTimeout(timeout time.Duration) *AddCardParams {
	return &AddCardParams{
		timeout: timeout,
	}
}

// NewAddCardParamsWithContext creates a new AddCardParams object
// with the ability to set a context for a request.
func NewAddCardParamsWithContext(ctx context.Context) *AddCardParams {
	return &AddCardParams{
		Context: ctx,
	}
}

// NewAddCardParamsWithHTTPClient creates a new AddCardParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddCardParamsWithHTTPClient(client *http.Client) *AddCardParams {
	return &AddCardParams{
		HTTPClient: client,
	}
}

/*
AddCardParams contains all the parameters to send to the API endpoint

	for the add card operation.

	Typically these are written to a http.Request.
*/
type AddCardParams struct {

	/* Card.

	   card to add
	*/
	Card *models.Card

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add card params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCardParams) WithDefaults() *AddCardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add card params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddCardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add card params
func (o *AddCardParams) WithTimeout(timeout time.Duration) *AddCardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add card params
func (o *AddCardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add card params
func (o *AddCardParams) WithContext(ctx context.Context) *AddCardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add card params
func (o *AddCardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add card params
func (o *AddCardParams) WithHTTPClient(client *http.Client) *AddCardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add card params
func (o *AddCardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCard adds the card to the add card params
func (o *AddCardParams) WithCard(card *models.Card) *AddCardParams {
	o.SetCard(card)
	return o
}

// SetCard adds the card to the add card params
func (o *AddCardParams) SetCard(card *models.Card) {
	o.Card = card
}

// WriteToRequest writes these params to a swagger request
func (o *AddCardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Card != nil {
		if err := r.SetBodyParam(o.Card); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
