// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddbankReader is a Reader for the Addbank structure.
type AddbankReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddbankReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddbankCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddbankBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAddbankConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /banks] addbank", response, response.Code())
	}
}

// NewAddbankCreated creates a AddbankCreated with default headers values
func NewAddbankCreated() *AddbankCreated {
	return &AddbankCreated{}
}

/*
AddbankCreated describes a response with status code 201, with default header values.

bank created
*/
type AddbankCreated struct {
}

// IsSuccess returns true when this addbank created response has a 2xx status code
func (o *AddbankCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this addbank created response has a 3xx status code
func (o *AddbankCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this addbank created response has a 4xx status code
func (o *AddbankCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this addbank created response has a 5xx status code
func (o *AddbankCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this addbank created response a status code equal to that given
func (o *AddbankCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the addbank created response
func (o *AddbankCreated) Code() int {
	return 201
}

func (o *AddbankCreated) Error() string {
	return fmt.Sprintf("[POST /banks][%d] addbankCreated", 201)
}

func (o *AddbankCreated) String() string {
	return fmt.Sprintf("[POST /banks][%d] addbankCreated", 201)
}

func (o *AddbankCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddbankBadRequest creates a AddbankBadRequest with default headers values
func NewAddbankBadRequest() *AddbankBadRequest {
	return &AddbankBadRequest{}
}

/*
AddbankBadRequest describes a response with status code 400, with default header values.

invalid input, object invalid
*/
type AddbankBadRequest struct {
}

// IsSuccess returns true when this addbank bad request response has a 2xx status code
func (o *AddbankBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this addbank bad request response has a 3xx status code
func (o *AddbankBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this addbank bad request response has a 4xx status code
func (o *AddbankBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this addbank bad request response has a 5xx status code
func (o *AddbankBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this addbank bad request response a status code equal to that given
func (o *AddbankBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the addbank bad request response
func (o *AddbankBadRequest) Code() int {
	return 400
}

func (o *AddbankBadRequest) Error() string {
	return fmt.Sprintf("[POST /banks][%d] addbankBadRequest", 400)
}

func (o *AddbankBadRequest) String() string {
	return fmt.Sprintf("[POST /banks][%d] addbankBadRequest", 400)
}

func (o *AddbankBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddbankConflict creates a AddbankConflict with default headers values
func NewAddbankConflict() *AddbankConflict {
	return &AddbankConflict{}
}

/*
AddbankConflict describes a response with status code 409, with default header values.

bank already exists
*/
type AddbankConflict struct {
}

// IsSuccess returns true when this addbank conflict response has a 2xx status code
func (o *AddbankConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this addbank conflict response has a 3xx status code
func (o *AddbankConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this addbank conflict response has a 4xx status code
func (o *AddbankConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this addbank conflict response has a 5xx status code
func (o *AddbankConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this addbank conflict response a status code equal to that given
func (o *AddbankConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the addbank conflict response
func (o *AddbankConflict) Code() int {
	return 409
}

func (o *AddbankConflict) Error() string {
	return fmt.Sprintf("[POST /banks][%d] addbankConflict", 409)
}

func (o *AddbankConflict) String() string {
	return fmt.Sprintf("[POST /banks][%d] addbankConflict", 409)
}

func (o *AddbankConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
