// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDelPersonParams creates a new DelPersonParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelPersonParams() *DelPersonParams {
	return &DelPersonParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelPersonParamsWithTimeout creates a new DelPersonParams object
// with the ability to set a timeout on a request.
func NewDelPersonParamsWithTimeout(timeout time.Duration) *DelPersonParams {
	return &DelPersonParams{
		timeout: timeout,
	}
}

// NewDelPersonParamsWithContext creates a new DelPersonParams object
// with the ability to set a context for a request.
func NewDelPersonParamsWithContext(ctx context.Context) *DelPersonParams {
	return &DelPersonParams{
		Context: ctx,
	}
}

// NewDelPersonParamsWithHTTPClient creates a new DelPersonParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelPersonParamsWithHTTPClient(client *http.Client) *DelPersonParams {
	return &DelPersonParams{
		HTTPClient: client,
	}
}

/*
DelPersonParams contains all the parameters to send to the API endpoint

	for the del person operation.

	Typically these are written to a http.Request.
*/
type DelPersonParams struct {

	/* Inn.

	   Person to remove
	*/
	Inn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the del person params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelPersonParams) WithDefaults() *DelPersonParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the del person params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelPersonParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the del person params
func (o *DelPersonParams) WithTimeout(timeout time.Duration) *DelPersonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the del person params
func (o *DelPersonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the del person params
func (o *DelPersonParams) WithContext(ctx context.Context) *DelPersonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the del person params
func (o *DelPersonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the del person params
func (o *DelPersonParams) WithHTTPClient(client *http.Client) *DelPersonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the del person params
func (o *DelPersonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInn adds the inn to the del person params
func (o *DelPersonParams) WithInn(inn int64) *DelPersonParams {
	o.SetInn(inn)
	return o
}

// SetInn adds the inn to the del person params
func (o *DelPersonParams) SetInn(inn int64) {
	o.Inn = inn
}

// WriteToRequest writes these params to a swagger request
func (o *DelPersonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inn
	if err := r.SetPathParam("inn", swag.FormatInt64(o.Inn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
