// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDelBankParams creates a new DelBankParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelBankParams() *DelBankParams {
	return &DelBankParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelBankParamsWithTimeout creates a new DelBankParams object
// with the ability to set a timeout on a request.
func NewDelBankParamsWithTimeout(timeout time.Duration) *DelBankParams {
	return &DelBankParams{
		timeout: timeout,
	}
}

// NewDelBankParamsWithContext creates a new DelBankParams object
// with the ability to set a context for a request.
func NewDelBankParamsWithContext(ctx context.Context) *DelBankParams {
	return &DelBankParams{
		Context: ctx,
	}
}

// NewDelBankParamsWithHTTPClient creates a new DelBankParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelBankParamsWithHTTPClient(client *http.Client) *DelBankParams {
	return &DelBankParams{
		HTTPClient: client,
	}
}

/*
DelBankParams contains all the parameters to send to the API endpoint

	for the del bank operation.

	Typically these are written to a http.Request.
*/
type DelBankParams struct {

	/* Inn.

	   bank to remove
	*/
	Inn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the del bank params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelBankParams) WithDefaults() *DelBankParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the del bank params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelBankParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the del bank params
func (o *DelBankParams) WithTimeout(timeout time.Duration) *DelBankParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the del bank params
func (o *DelBankParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the del bank params
func (o *DelBankParams) WithContext(ctx context.Context) *DelBankParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the del bank params
func (o *DelBankParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the del bank params
func (o *DelBankParams) WithHTTPClient(client *http.Client) *DelBankParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the del bank params
func (o *DelBankParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInn adds the inn to the del bank params
func (o *DelBankParams) WithInn(inn int64) *DelBankParams {
	o.SetInn(inn)
	return o
}

// SetInn adds the inn to the del bank params
func (o *DelBankParams) SetInn(inn int64) {
	o.Inn = inn
}

// WriteToRequest writes these params to a swagger request
func (o *DelBankParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inn
	if err := r.SetPathParam("inn", swag.FormatInt64(o.Inn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
