// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DelСardReader is a Reader for the DelСard structure.
type DelСardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelСardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDelСardNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDelСardBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDelСardConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /cards/{inn}] delСard", response, response.Code())
	}
}

// NewDelСardNoContent creates a DelСardNoContent with default headers values
func NewDelСardNoContent() *DelСardNoContent {
	return &DelСardNoContent{}
}

/*
DelСardNoContent describes a response with status code 204, with default header values.

card deleted
*/
type DelСardNoContent struct {
}

// IsSuccess returns true when this del сard no content response has a 2xx status code
func (o *DelСardNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this del сard no content response has a 3xx status code
func (o *DelСardNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del сard no content response has a 4xx status code
func (o *DelСardNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this del сard no content response has a 5xx status code
func (o *DelСardNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this del сard no content response a status code equal to that given
func (o *DelСardNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the del сard no content response
func (o *DelСardNoContent) Code() int {
	return 204
}

func (o *DelСardNoContent) Error() string {
	return fmt.Sprintf("[DELETE /cards/{inn}][%d] delСardNoContent", 204)
}

func (o *DelСardNoContent) String() string {
	return fmt.Sprintf("[DELETE /cards/{inn}][%d] delСardNoContent", 204)
}

func (o *DelСardNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDelСardBadRequest creates a DelСardBadRequest with default headers values
func NewDelСardBadRequest() *DelСardBadRequest {
	return &DelСardBadRequest{}
}

/*
DelСardBadRequest describes a response with status code 400, with default header values.

invalid input, object invalid
*/
type DelСardBadRequest struct {
}

// IsSuccess returns true when this del сard bad request response has a 2xx status code
func (o *DelСardBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del сard bad request response has a 3xx status code
func (o *DelСardBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del сard bad request response has a 4xx status code
func (o *DelСardBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this del сard bad request response has a 5xx status code
func (o *DelСardBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this del сard bad request response a status code equal to that given
func (o *DelСardBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the del сard bad request response
func (o *DelСardBadRequest) Code() int {
	return 400
}

func (o *DelСardBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /cards/{inn}][%d] delСardBadRequest", 400)
}

func (o *DelСardBadRequest) String() string {
	return fmt.Sprintf("[DELETE /cards/{inn}][%d] delСardBadRequest", 400)
}

func (o *DelСardBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDelСardConflict creates a DelСardConflict with default headers values
func NewDelСardConflict() *DelСardConflict {
	return &DelСardConflict{}
}

/*
DelСardConflict describes a response with status code 409, with default header values.

card not exists
*/
type DelСardConflict struct {
}

// IsSuccess returns true when this del сard conflict response has a 2xx status code
func (o *DelСardConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del сard conflict response has a 3xx status code
func (o *DelСardConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del сard conflict response has a 4xx status code
func (o *DelСardConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this del сard conflict response has a 5xx status code
func (o *DelСardConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this del сard conflict response a status code equal to that given
func (o *DelСardConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the del сard conflict response
func (o *DelСardConflict) Code() int {
	return 409
}

func (o *DelСardConflict) Error() string {
	return fmt.Sprintf("[DELETE /cards/{inn}][%d] delСardConflict", 409)
}

func (o *DelСardConflict) String() string {
	return fmt.Sprintf("[DELETE /cards/{inn}][%d] delСardConflict", 409)
}

func (o *DelСardConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
