// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDelСardParams creates a new DelСardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelСardParams() *DelСardParams {
	return &DelСardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelСardParamsWithTimeout creates a new DelСardParams object
// with the ability to set a timeout on a request.
func NewDelСardParamsWithTimeout(timeout time.Duration) *DelСardParams {
	return &DelСardParams{
		timeout: timeout,
	}
}

// NewDelСardParamsWithContext creates a new DelСardParams object
// with the ability to set a context for a request.
func NewDelСardParamsWithContext(ctx context.Context) *DelСardParams {
	return &DelСardParams{
		Context: ctx,
	}
}

// NewDelСardParamsWithHTTPClient creates a new DelСardParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelСardParamsWithHTTPClient(client *http.Client) *DelСardParams {
	return &DelСardParams{
		HTTPClient: client,
	}
}

/*
DelСardParams contains all the parameters to send to the API endpoint

	for the del сard operation.

	Typically these are written to a http.Request.
*/
type DelСardParams struct {

	/* Inn.

	   card to remove
	*/
	Inn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the del сard params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelСardParams) WithDefaults() *DelСardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the del сard params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelСardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the del сard params
func (o *DelСardParams) WithTimeout(timeout time.Duration) *DelСardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the del сard params
func (o *DelСardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the del сard params
func (o *DelСardParams) WithContext(ctx context.Context) *DelСardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the del сard params
func (o *DelСardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the del сard params
func (o *DelСardParams) WithHTTPClient(client *http.Client) *DelСardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the del сard params
func (o *DelСardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInn adds the inn to the del сard params
func (o *DelСardParams) WithInn(inn int64) *DelСardParams {
	o.SetInn(inn)
	return o
}

// SetInn adds the inn to the del сard params
func (o *DelСardParams) SetInn(inn int64) {
	o.Inn = inn
}

// WriteToRequest writes these params to a swagger request
func (o *DelСardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inn
	if err := r.SetPathParam("inn", swag.FormatInt64(o.Inn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
