// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DelBankReader is a Reader for the DelBank structure.
type DelBankReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelBankReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDelBankNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDelBankBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDelBankConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /banks/{inn}] delBank", response, response.Code())
	}
}

// NewDelBankNoContent creates a DelBankNoContent with default headers values
func NewDelBankNoContent() *DelBankNoContent {
	return &DelBankNoContent{}
}

/*
DelBankNoContent describes a response with status code 204, with default header values.

bank deleted
*/
type DelBankNoContent struct {
}

// IsSuccess returns true when this del bank no content response has a 2xx status code
func (o *DelBankNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this del bank no content response has a 3xx status code
func (o *DelBankNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del bank no content response has a 4xx status code
func (o *DelBankNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this del bank no content response has a 5xx status code
func (o *DelBankNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this del bank no content response a status code equal to that given
func (o *DelBankNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the del bank no content response
func (o *DelBankNoContent) Code() int {
	return 204
}

func (o *DelBankNoContent) Error() string {
	return fmt.Sprintf("[DELETE /banks/{inn}][%d] delBankNoContent", 204)
}

func (o *DelBankNoContent) String() string {
	return fmt.Sprintf("[DELETE /banks/{inn}][%d] delBankNoContent", 204)
}

func (o *DelBankNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDelBankBadRequest creates a DelBankBadRequest with default headers values
func NewDelBankBadRequest() *DelBankBadRequest {
	return &DelBankBadRequest{}
}

/*
DelBankBadRequest describes a response with status code 400, with default header values.

invalid input, object invalid
*/
type DelBankBadRequest struct {
}

// IsSuccess returns true when this del bank bad request response has a 2xx status code
func (o *DelBankBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del bank bad request response has a 3xx status code
func (o *DelBankBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del bank bad request response has a 4xx status code
func (o *DelBankBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this del bank bad request response has a 5xx status code
func (o *DelBankBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this del bank bad request response a status code equal to that given
func (o *DelBankBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the del bank bad request response
func (o *DelBankBadRequest) Code() int {
	return 400
}

func (o *DelBankBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /banks/{inn}][%d] delBankBadRequest", 400)
}

func (o *DelBankBadRequest) String() string {
	return fmt.Sprintf("[DELETE /banks/{inn}][%d] delBankBadRequest", 400)
}

func (o *DelBankBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDelBankConflict creates a DelBankConflict with default headers values
func NewDelBankConflict() *DelBankConflict {
	return &DelBankConflict{}
}

/*
DelBankConflict describes a response with status code 409, with default header values.

bank not exists
*/
type DelBankConflict struct {
}

// IsSuccess returns true when this del bank conflict response has a 2xx status code
func (o *DelBankConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del bank conflict response has a 3xx status code
func (o *DelBankConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del bank conflict response has a 4xx status code
func (o *DelBankConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this del bank conflict response has a 5xx status code
func (o *DelBankConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this del bank conflict response a status code equal to that given
func (o *DelBankConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the del bank conflict response
func (o *DelBankConflict) Code() int {
	return 409
}

func (o *DelBankConflict) Error() string {
	return fmt.Sprintf("[DELETE /banks/{inn}][%d] delBankConflict", 409)
}

func (o *DelBankConflict) String() string {
	return fmt.Sprintf("[DELETE /banks/{inn}][%d] delBankConflict", 409)
}

func (o *DelBankConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
