// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCardReader is a Reader for the GetCard structure.
type GetCardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGetCardCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCardBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetCardConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cards/{inn}] getCard", response, response.Code())
	}
}

// NewGetCardCreated creates a GetCardCreated with default headers values
func NewGetCardCreated() *GetCardCreated {
	return &GetCardCreated{}
}

/*
GetCardCreated describes a response with status code 201, with default header values.

card found
*/
type GetCardCreated struct {
}

// IsSuccess returns true when this get card created response has a 2xx status code
func (o *GetCardCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get card created response has a 3xx status code
func (o *GetCardCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get card created response has a 4xx status code
func (o *GetCardCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this get card created response has a 5xx status code
func (o *GetCardCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this get card created response a status code equal to that given
func (o *GetCardCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the get card created response
func (o *GetCardCreated) Code() int {
	return 201
}

func (o *GetCardCreated) Error() string {
	return fmt.Sprintf("[GET /cards/{inn}][%d] getCardCreated", 201)
}

func (o *GetCardCreated) String() string {
	return fmt.Sprintf("[GET /cards/{inn}][%d] getCardCreated", 201)
}

func (o *GetCardCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCardBadRequest creates a GetCardBadRequest with default headers values
func NewGetCardBadRequest() *GetCardBadRequest {
	return &GetCardBadRequest{}
}

/*
GetCardBadRequest describes a response with status code 400, with default header values.

invalid input, object invalid
*/
type GetCardBadRequest struct {
}

// IsSuccess returns true when this get card bad request response has a 2xx status code
func (o *GetCardBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get card bad request response has a 3xx status code
func (o *GetCardBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get card bad request response has a 4xx status code
func (o *GetCardBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get card bad request response has a 5xx status code
func (o *GetCardBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get card bad request response a status code equal to that given
func (o *GetCardBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get card bad request response
func (o *GetCardBadRequest) Code() int {
	return 400
}

func (o *GetCardBadRequest) Error() string {
	return fmt.Sprintf("[GET /cards/{inn}][%d] getCardBadRequest", 400)
}

func (o *GetCardBadRequest) String() string {
	return fmt.Sprintf("[GET /cards/{inn}][%d] getCardBadRequest", 400)
}

func (o *GetCardBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCardConflict creates a GetCardConflict with default headers values
func NewGetCardConflict() *GetCardConflict {
	return &GetCardConflict{}
}

/*
GetCardConflict describes a response with status code 409, with default header values.

card not exists
*/
type GetCardConflict struct {
}

// IsSuccess returns true when this get card conflict response has a 2xx status code
func (o *GetCardConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get card conflict response has a 3xx status code
func (o *GetCardConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get card conflict response has a 4xx status code
func (o *GetCardConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get card conflict response has a 5xx status code
func (o *GetCardConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get card conflict response a status code equal to that given
func (o *GetCardConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get card conflict response
func (o *GetCardConflict) Code() int {
	return 409
}

func (o *GetCardConflict) Error() string {
	return fmt.Sprintf("[GET /cards/{inn}][%d] getCardConflict", 409)
}

func (o *GetCardConflict) String() string {
	return fmt.Sprintf("[GET /cards/{inn}][%d] getCardConflict", 409)
}

func (o *GetCardConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
