// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetPersonParams creates a new GetPersonParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPersonParams() *GetPersonParams {
	return &GetPersonParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPersonParamsWithTimeout creates a new GetPersonParams object
// with the ability to set a timeout on a request.
func NewGetPersonParamsWithTimeout(timeout time.Duration) *GetPersonParams {
	return &GetPersonParams{
		timeout: timeout,
	}
}

// NewGetPersonParamsWithContext creates a new GetPersonParams object
// with the ability to set a context for a request.
func NewGetPersonParamsWithContext(ctx context.Context) *GetPersonParams {
	return &GetPersonParams{
		Context: ctx,
	}
}

// NewGetPersonParamsWithHTTPClient creates a new GetPersonParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPersonParamsWithHTTPClient(client *http.Client) *GetPersonParams {
	return &GetPersonParams{
		HTTPClient: client,
	}
}

/*
GetPersonParams contains all the parameters to send to the API endpoint

	for the get person operation.

	Typically these are written to a http.Request.
*/
type GetPersonParams struct {

	/* Inn.

	   get person
	*/
	Inn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get person params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPersonParams) WithDefaults() *GetPersonParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get person params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPersonParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get person params
func (o *GetPersonParams) WithTimeout(timeout time.Duration) *GetPersonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get person params
func (o *GetPersonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get person params
func (o *GetPersonParams) WithContext(ctx context.Context) *GetPersonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get person params
func (o *GetPersonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get person params
func (o *GetPersonParams) WithHTTPClient(client *http.Client) *GetPersonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get person params
func (o *GetPersonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInn adds the inn to the get person params
func (o *GetPersonParams) WithInn(inn int64) *GetPersonParams {
	o.SetInn(inn)
	return o
}

// SetInn adds the inn to the get person params
func (o *GetPersonParams) SetInn(inn int64) {
	o.Inn = inn
}

// WriteToRequest writes these params to a swagger request
func (o *GetPersonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inn
	if err := r.SetPathParam("inn", swag.FormatInt64(o.Inn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
