// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetBankReader is a Reader for the GetBank structure.
type GetBankReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBankReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGetBankCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBankBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetBankConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /banks/{inn}] getBank", response, response.Code())
	}
}

// NewGetBankCreated creates a GetBankCreated with default headers values
func NewGetBankCreated() *GetBankCreated {
	return &GetBankCreated{}
}

/*
GetBankCreated describes a response with status code 201, with default header values.

bank found
*/
type GetBankCreated struct {
}

// IsSuccess returns true when this get bank created response has a 2xx status code
func (o *GetBankCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get bank created response has a 3xx status code
func (o *GetBankCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bank created response has a 4xx status code
func (o *GetBankCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this get bank created response has a 5xx status code
func (o *GetBankCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this get bank created response a status code equal to that given
func (o *GetBankCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the get bank created response
func (o *GetBankCreated) Code() int {
	return 201
}

func (o *GetBankCreated) Error() string {
	return fmt.Sprintf("[GET /banks/{inn}][%d] getBankCreated", 201)
}

func (o *GetBankCreated) String() string {
	return fmt.Sprintf("[GET /banks/{inn}][%d] getBankCreated", 201)
}

func (o *GetBankCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBankBadRequest creates a GetBankBadRequest with default headers values
func NewGetBankBadRequest() *GetBankBadRequest {
	return &GetBankBadRequest{}
}

/*
GetBankBadRequest describes a response with status code 400, with default header values.

invalid input, object invalid
*/
type GetBankBadRequest struct {
}

// IsSuccess returns true when this get bank bad request response has a 2xx status code
func (o *GetBankBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bank bad request response has a 3xx status code
func (o *GetBankBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bank bad request response has a 4xx status code
func (o *GetBankBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get bank bad request response has a 5xx status code
func (o *GetBankBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get bank bad request response a status code equal to that given
func (o *GetBankBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get bank bad request response
func (o *GetBankBadRequest) Code() int {
	return 400
}

func (o *GetBankBadRequest) Error() string {
	return fmt.Sprintf("[GET /banks/{inn}][%d] getBankBadRequest", 400)
}

func (o *GetBankBadRequest) String() string {
	return fmt.Sprintf("[GET /banks/{inn}][%d] getBankBadRequest", 400)
}

func (o *GetBankBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBankConflict creates a GetBankConflict with default headers values
func NewGetBankConflict() *GetBankConflict {
	return &GetBankConflict{}
}

/*
GetBankConflict describes a response with status code 409, with default header values.

bank not exists
*/
type GetBankConflict struct {
}

// IsSuccess returns true when this get bank conflict response has a 2xx status code
func (o *GetBankConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bank conflict response has a 3xx status code
func (o *GetBankConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bank conflict response has a 4xx status code
func (o *GetBankConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get bank conflict response has a 5xx status code
func (o *GetBankConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get bank conflict response a status code equal to that given
func (o *GetBankConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get bank conflict response
func (o *GetBankConflict) Code() int {
	return 409
}

func (o *GetBankConflict) Error() string {
	return fmt.Sprintf("[GET /banks/{inn}][%d] getBankConflict", 409)
}

func (o *GetBankConflict) String() string {
	return fmt.Sprintf("[GET /banks/{inn}][%d] getBankConflict", 409)
}

func (o *GetBankConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
