// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBankParams creates a new GetBankParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBankParams() *GetBankParams {
	return &GetBankParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBankParamsWithTimeout creates a new GetBankParams object
// with the ability to set a timeout on a request.
func NewGetBankParamsWithTimeout(timeout time.Duration) *GetBankParams {
	return &GetBankParams{
		timeout: timeout,
	}
}

// NewGetBankParamsWithContext creates a new GetBankParams object
// with the ability to set a context for a request.
func NewGetBankParamsWithContext(ctx context.Context) *GetBankParams {
	return &GetBankParams{
		Context: ctx,
	}
}

// NewGetBankParamsWithHTTPClient creates a new GetBankParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBankParamsWithHTTPClient(client *http.Client) *GetBankParams {
	return &GetBankParams{
		HTTPClient: client,
	}
}

/*
GetBankParams contains all the parameters to send to the API endpoint

	for the get bank operation.

	Typically these are written to a http.Request.
*/
type GetBankParams struct {

	/* Inn.

	   get bank
	*/
	Inn int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bank params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBankParams) WithDefaults() *GetBankParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bank params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBankParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bank params
func (o *GetBankParams) WithTimeout(timeout time.Duration) *GetBankParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bank params
func (o *GetBankParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bank params
func (o *GetBankParams) WithContext(ctx context.Context) *GetBankParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bank params
func (o *GetBankParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bank params
func (o *GetBankParams) WithHTTPClient(client *http.Client) *GetBankParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bank params
func (o *GetBankParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInn adds the inn to the get bank params
func (o *GetBankParams) WithInn(inn int64) *GetBankParams {
	o.SetInn(inn)
	return o
}

// SetInn adds the inn to the get bank params
func (o *GetBankParams) SetInn(inn int64) {
	o.Inn = inn
}

// WriteToRequest writes these params to a swagger request
func (o *GetBankParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inn
	if err := r.SetPathParam("inn", swag.FormatInt64(o.Inn)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
