// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"bank-microservice/api/models"
)

// GetPersonsReader is a Reader for the GetPersons structure.
type GetPersonsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPersonsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPersonsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPersonsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /persons] GetPersons", response, response.Code())
	}
}

// NewGetPersonsOK creates a GetPersonsOK with default headers values
func NewGetPersonsOK() *GetPersonsOK {
	return &GetPersonsOK{}
}

/*
GetPersonsOK describes a response with status code 200, with default header values.

search results matching criteria
*/
type GetPersonsOK struct {
	Payload []*models.Person
}

// IsSuccess returns true when this get persons o k response has a 2xx status code
func (o *GetPersonsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get persons o k response has a 3xx status code
func (o *GetPersonsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get persons o k response has a 4xx status code
func (o *GetPersonsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get persons o k response has a 5xx status code
func (o *GetPersonsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get persons o k response a status code equal to that given
func (o *GetPersonsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get persons o k response
func (o *GetPersonsOK) Code() int {
	return 200
}

func (o *GetPersonsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /persons][%d] getPersonsOK %s", 200, payload)
}

func (o *GetPersonsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /persons][%d] getPersonsOK %s", 200, payload)
}

func (o *GetPersonsOK) GetPayload() []*models.Person {
	return o.Payload
}

func (o *GetPersonsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPersonsBadRequest creates a GetPersonsBadRequest with default headers values
func NewGetPersonsBadRequest() *GetPersonsBadRequest {
	return &GetPersonsBadRequest{}
}

/*
GetPersonsBadRequest describes a response with status code 400, with default header values.

bad input parameter
*/
type GetPersonsBadRequest struct {
}

// IsSuccess returns true when this get persons bad request response has a 2xx status code
func (o *GetPersonsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get persons bad request response has a 3xx status code
func (o *GetPersonsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get persons bad request response has a 4xx status code
func (o *GetPersonsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get persons bad request response has a 5xx status code
func (o *GetPersonsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get persons bad request response a status code equal to that given
func (o *GetPersonsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get persons bad request response
func (o *GetPersonsBadRequest) Code() int {
	return 400
}

func (o *GetPersonsBadRequest) Error() string {
	return fmt.Sprintf("[GET /persons][%d] getPersonsBadRequest", 400)
}

func (o *GetPersonsBadRequest) String() string {
	return fmt.Sprintf("[GET /persons][%d] getPersonsBadRequest", 400)
}

func (o *GetPersonsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
