// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIsValidParams creates a new IsValidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIsValidParams() *IsValidParams {
	return &IsValidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIsValidParamsWithTimeout creates a new IsValidParams object
// with the ability to set a timeout on a request.
func NewIsValidParamsWithTimeout(timeout time.Duration) *IsValidParams {
	return &IsValidParams{
		timeout: timeout,
	}
}

// NewIsValidParamsWithContext creates a new IsValidParams object
// with the ability to set a context for a request.
func NewIsValidParamsWithContext(ctx context.Context) *IsValidParams {
	return &IsValidParams{
		Context: ctx,
	}
}

// NewIsValidParamsWithHTTPClient creates a new IsValidParams object
// with the ability to set a custom HTTPClient for a request.
func NewIsValidParamsWithHTTPClient(client *http.Client) *IsValidParams {
	return &IsValidParams{
		HTTPClient: client,
	}
}

/*
IsValidParams contains all the parameters to send to the API endpoint

	for the is valid operation.

	Typically these are written to a http.Request.
*/
type IsValidParams struct {

	/* ID.

	   get card status
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the is valid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IsValidParams) WithDefaults() *IsValidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the is valid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IsValidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the is valid params
func (o *IsValidParams) WithTimeout(timeout time.Duration) *IsValidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is valid params
func (o *IsValidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is valid params
func (o *IsValidParams) WithContext(ctx context.Context) *IsValidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is valid params
func (o *IsValidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is valid params
func (o *IsValidParams) WithHTTPClient(client *http.Client) *IsValidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is valid params
func (o *IsValidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the is valid params
func (o *IsValidParams) WithID(id int64) *IsValidParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the is valid params
func (o *IsValidParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *IsValidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
