package bootstrap

import (
	"bank-microservice/internal/infrastructure/database"
	"bank-microservice/internal/repositories"
	"bank-microservice/internal/services"
	"bank-microservice/internal/services/bank"
	"bank-microservice/internal/services/card"
	"bank-microservice/internal/services/person"
	"context"
	"fmt"

	"log"
	"os"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"bank-microservice/internal/infrastructure/http/httpserver"
	"bank-microservice/internal/infrastructure/http/httpserver/swaggerapi"
)

// Инициализация и запуск сервера

type Bootstrapper struct {
	// Вложенность как в пакетах
	//conltroller *controllers.
	//database
	DB           *database.Database
	Repositories *repositories.Repositories
	Services     services.Services
}

func New() (*Bootstrapper, error) {
	var (
		ctx          = context.Background()
		bootstrapper = &Bootstrapper{}
		err          error
	)

	// init storage
	bootstrapper.DB, err = database.New(ctx)
	if err != nil {
		return nil, err
	}

	// init repository
	bootstrapper.Repositories = repositories.NewRepository(bootstrapper.DB)

	// init service
	bootstrapper.initService()

	// bootstrap complete
	return bootstrapper, nil
}

func (b *Bootstrapper) initService() {
	b.Services = services.Services{
		Card:   card.NewService(b.Repositories.Card),
		Bank:   bank.NewService(b.Repositories.Bank),
		Person: person.NewService(b.Repositories.Person),
	}
}

func (b *Bootstrapper) RunAPI() {
	// This file was generated by the swagger tool.
	// Make sure not to overwrite this file after you generated it because all your edits would be lost!

	fmt.Println("Bootstrapper.RunAPI()")
	swaggerSpec, err := loads.Embedded(httpserver.SwaggerJSON, httpserver.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := swaggerapi.NewBcardMicroserviceAPIAPI(swaggerSpec)
	server := httpserver.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "bcard_microservice_api"
	parser.LongDescription = "Sample OpenAPI2.0 spec for demo microservice bcard:\nCheck valid paycard (exist & not expiried)\nCRUD Card, Person, Bank & check valid\n\n"
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
