// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPersonsHandlerFunc turns a function with the right signature into a get persons handler
type GetPersonsHandlerFunc func(GetPersonsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPersonsHandlerFunc) Handle(params GetPersonsParams) middleware.Responder {
	return fn(params)
}

// GetPersonsHandler interface for that can handle valid get persons params
type GetPersonsHandler interface {
	Handle(GetPersonsParams) middleware.Responder
}

// NewGetPersons creates a new http.Handler for the get persons operation
func NewGetPersons(ctx *middleware.Context, handler GetPersonsHandler) *GetPersons {
	return &GetPersons{Context: ctx, Handler: handler}
}

/*
	GetPersons swagger:route GET /persons admins getPersons

searches persons

By passing in the appropriate options, you can search for
persons in the system
*/
type GetPersons struct {
	Context *middleware.Context
	Handler GetPersonsHandler
}

func (o *GetPersons) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPersonsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetPersonsOKBodyItems0 Sample person model
//
// swagger:model GetPersonsOKBodyItems0
type GetPersonsOKBodyItems0 struct {

	// inn
	// Example: 123456789012
	// Required: true
	Inn *uint64 `json:"inn"`

	// name
	// Example: John Smith
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this get persons o k body items0
func (o *GetPersonsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInn(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPersonsOKBodyItems0) validateInn(formats strfmt.Registry) error {

	if err := validate.Required("inn", "body", o.Inn); err != nil {
		return err
	}

	return nil
}

func (o *GetPersonsOKBodyItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get persons o k body items0 based on context it is used
func (o *GetPersonsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPersonsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPersonsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetPersonsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
