// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IsValidHandlerFunc turns a function with the right signature into a is valid handler
type IsValidHandlerFunc func(IsValidParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IsValidHandlerFunc) Handle(params IsValidParams) middleware.Responder {
	return fn(params)
}

// IsValidHandler interface for that can handle valid is valid params
type IsValidHandler interface {
	Handle(IsValidParams) middleware.Responder
}

// NewIsValid creates a new http.Handler for the is valid operation
func NewIsValid(ctx *middleware.Context, handler IsValidHandler) *IsValid {
	return &IsValid{Context: ctx, Handler: handler}
}

/*
	IsValid swagger:route GET /card/validator/{id} admins service isValid

check valid card (exist&expires)

Check card status: if card.exists & card.Expires>now() & valid = true
*/
type IsValid struct {
	Context *middleware.Context
	Handler IsValidHandler
}

func (o *IsValid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIsValidParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// IsValidOKBodyItems0 Sample card model
//
// swagger:model IsValidOKBodyItems0
type IsValidOKBodyItems0 struct {

	// bic
	// Example: 123456789
	// Required: true
	Bic *uint32 `json:"bic"`

	// expires
	// Example: 2016-08-29T09:12:33.001Z
	// Required: true
	// Format: date-time
	Expires *strfmt.DateTime `json:"expires"`

	// id
	// Example: 1234123412341234
	// Required: true
	ID *uint64 `json:"id"`

	// name
	// Example: Bank of Albania
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this is valid o k body items0
func (o *IsValidOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBic(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateExpires(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IsValidOKBodyItems0) validateBic(formats strfmt.Registry) error {

	if err := validate.Required("bic", "body", o.Bic); err != nil {
		return err
	}

	return nil
}

func (o *IsValidOKBodyItems0) validateExpires(formats strfmt.Registry) error {

	if err := validate.Required("expires", "body", o.Expires); err != nil {
		return err
	}

	if err := validate.FormatOf("expires", "body", "date-time", o.Expires.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *IsValidOKBodyItems0) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *IsValidOKBodyItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this is valid o k body items0 based on context it is used
func (o *IsValidOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *IsValidOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IsValidOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res IsValidOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
