// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewBankHandlerFunc turns a function with the right signature into a new bank handler
type NewBankHandlerFunc func(NewBankParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NewBankHandlerFunc) Handle(params NewBankParams) middleware.Responder {
	return fn(params)
}

// NewBankHandler interface for that can handle valid new bank params
type NewBankHandler interface {
	Handle(NewBankParams) middleware.Responder
}

// NewNewBank creates a new http.Handler for the new bank operation
func NewNewBank(ctx *middleware.Context, handler NewBankHandler) *NewBank {
	return &NewBank{Context: ctx, Handler: handler}
}

/*
	NewBank swagger:route POST /banks admins newBank

adds an bank item

Adds new bank to the system
*/
type NewBank struct {
	Context *middleware.Context
	Handler NewBankHandler
}

func (o *NewBank) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNewBankParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// NewBankBody Sample bank model
//
// swagger:model NewBankBody
type NewBankBody struct {

	// bic
	// Example: 123456789
	// Required: true
	Bic *uint32 `json:"bic"`

	// name
	// Example: Bank of Albania
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this new bank body
func (o *NewBankBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBic(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NewBankBody) validateBic(formats strfmt.Registry) error {

	if err := validate.Required("bank"+"."+"bic", "body", o.Bic); err != nil {
		return err
	}

	return nil
}

func (o *NewBankBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("bank"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this new bank body based on context it is used
func (o *NewBankBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *NewBankBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NewBankBody) UnmarshalBinary(b []byte) error {
	var res NewBankBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
